### ISSUE TITLE
['Missing dependency check] botan/botan.h missing

### ISSUE THREAD

**Issue by nikolajsheller** [bytting/libbitmessage#1]
Scanning dependencies of target libbitmessage
[ 14%] Building CXX object CMakeFiles/libbitmessage.dir/src/utils.cpp.o
~/bitmessage/libbitmessage/src/utils.cpp:22:25: fatal error: botan/botan.h: No such file or directory compilation terminated.

CMake should not attempt to build if libbotan is not available. Consider using FindBotan.cmake:
https://bitbucket.org/sergiu/botan-cmake/raw/c427e4189d7c40702b0d7ea4a2aeb5136b13f68b/FindBotan.cmake

**Comment by bytting** [comment]
I will look into that. Thanks a lot
